# -*- coding: utf-8 -*-
"""asl-image-classification-with-cnns-1-0-tes-2e676e.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OsxPAb7mgljIsnEDBU7Ethx6v2TxOGnY

# Import the required libraries
"""

import pandas as pd
import numpy as np
import tensorflow as tf

"""# Preprocessing the image data"""

#taking the train validation ratio as 4:1

batch_size=32
img_height=256
img_width=256


train_ds = tf.keras.utils.image_dataset_from_directory(
  "./Combined_Hand_Frames/",
  validation_split=0.2,
  subset="training",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

test_ds = tf.keras.utils.image_dataset_from_directory(
  "./Combined_Hand_Frames/",
  validation_split=0.2,
  subset="validation",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

class_names = train_ds.class_names
print("Class names:",class_names)
print("Total classes:",len(class_names))

"""# Modelling and training"""

#modelling

model = tf.keras.models.load_model('cnn.h5')

model.summary()

model.fit(train_ds, batch_size=32,validation_batch_size=32, validation_data=test_ds,epochs=3)

model.save('cnn_model.h5')

